apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: dev
spec:
  containers:
  - name: cont
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: devops
        mountPath: /opt/cont1
  volumes:
    - name: devops
      emptyDir: {}
