apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: test
    client: tcs
spec:
  containers:
    - name: con1
      image: shaikmustafa/dm
      ports: 
        - containerPort: 80
  nodeSelector:
    node: "minikube"